"""
ACTUAL WORKFLOW — Phase colormap → vertex colors

This script reproduces the exact steps used to generate vertex_colors.npy for
the rotating-wave brain render.

INPUTS  (phase_colormap.npy is generated by the analysis pipeline and is already
         registered to the Allen CCF atlas — load it directly):

    phase_colormap.npy   — shape (1320, 1140, 3) float32 in [0, 1].
                           Rows = AP axis (0 – 13 200 μm), cols = ML axis
                           (0 – 11 400 μm).  Cyclic colormap (e.g. CET_C6)
                           already applied.
    spiral_density.mat   — MATLAB file with 'unique_spirals' (N×3 float):
                           [AP_um, ML_um, density_count].  Convert once with
                           mat73 (see optional step 0b below).

OUTPUTS:
    root.obj             — whole-brain shell mesh (Allen CCF 25 μm)
    isocortex.obj        — dorsal cortex mesh
    vertices.npy         — isocortex vertex positions  (N, 3) float32
    faces.npy            — isocortex face indices
    vertex_colors.npy    — per-vertex RGBA for the phase map  (N, 4) float32

COORDINATE SYSTEM (Allen CCF 25 μm):
    Axis 0 = AP   0 – 13 200 μm   (image rows,    1 320 voxels)
    Axis 1 = DV   0 –  5 350 μm   (depth)
    Axis 2 = ML   0 – 11 400 μm   (image columns, 1 140 voxels)

    Verified from isocortex vertex ranges:
        axis 0: 1 803 – 10 373
        axis 1:   151 –  5 535
        axis 2:   502 – 10 873

Run in a normal Python environment (NOT inside Blender):
    pip install brainglobe-atlasapi trimesh scipy matplotlib numpy mat73
    python phase_colormap_workflow.py
"""

import numpy as np
import trimesh
from brainglobe_atlasapi import BrainGlobeAtlas
from scipy.interpolate import RegularGridInterpolator
import mat73

# ============================================================================
# STEP 0 — Convert .mat files to .npy (one-time)
# ============================================================================
# phase_colormap.mat is registered to the Allen CCF atlas by the analysis
# pipeline and saved as a MATLAB file.  Convert it once here.

data = mat73.loadmat("phase_colormap.mat")
phase_rgb = np.array(data["rgbImage"], dtype=np.float32)
if phase_rgb.max() > 1.0:       # convert uint8 → float32 [0, 1] if needed
    phase_rgb = phase_rgb / 255.0
np.save("phase_colormap.npy", phase_rgb)
print(f"phase_colormap.npy  shape={phase_rgb.shape}  "
      f"range=[{phase_rgb.min():.3f}, {phase_rgb.max():.3f}]")

data2 = mat73.loadmat("spiral_density.mat")
unique_spirals = np.array(data2["unique_spirals"], dtype=np.float32)
np.save("unique_spirals.npy", unique_spirals)
print(f"unique_spirals.npy  shape={unique_spirals.shape}")

# ============================================================================
# STEP 1 — Download Allen CCF 25 μm brain meshes
# ============================================================================
# First run downloads and caches the atlas (~hundreds of MB).

atlas = BrainGlobeAtlas("allen_mouse_25um")
atlas.mesh_from_structure("root").write("root.obj")
atlas.mesh_from_structure("Isocortex").write("isocortex.obj")
print("root.obj and isocortex.obj written.")

# ============================================================================
# STEP 2 — Load isocortex mesh and inspect axes
# ============================================================================
mesh     = trimesh.load("isocortex.obj")
vertices = mesh.vertices    # (N, 3) in Allen CCF μm
normals  = mesh.vertex_normals

print("Axis 0 range:", vertices[:, 0].min(), "–", vertices[:, 0].max())  # AP
print("Axis 1 range:", vertices[:, 1].min(), "–", vertices[:, 1].max())  # DV
print("Axis 2 range:", vertices[:, 2].min(), "–", vertices[:, 2].max())  # ML

# Save raw mesh arrays for inspection
np.save("vertices.npy", vertices.astype(np.float32))
np.save("faces.npy",    mesh.faces)

# ============================================================================
# STEP 3 — Interpolate phase colormap onto mesh vertices
# ============================================================================
phase_rgb = np.load("phase_colormap.npy")   # (1320, 1140, 3)
H, W = phase_rgb.shape[:2]

# Grid axes in Allen CCF μm (must span the full atlas extent)
ap_axis = np.linspace(0, 13200, H)   # 1320 × 25 μm
ml_axis = np.linspace(0, 11400, W)   # 1140 × 25 μm

def make_interp(channel):
    return RegularGridInterpolator(
        (ap_axis, ml_axis),
        phase_rgb[:, :, channel],
        method="linear",
        bounds_error=False,
        fill_value=np.nan,
    )

interp_r = make_interp(0)
interp_g = make_interp(1)
interp_b = make_interp(2)

# Query each vertex at its (AP, ML) position
# AP = axis 0 of mesh vertices;  ML = axis 2
query = np.column_stack([vertices[:, 0], vertices[:, 2]])
r = interp_r(query)
g = interp_g(query)
b = interp_b(query)

# ============================================================================
# STEP 4 — Assemble vertex color array, mark out-of-FOV vertices gray
# ============================================================================
GRAY    = [0.15, 0.15, 0.15, 1.0]
invalid = np.isnan(r)           # vertices outside the phase-map FOV

# Optional: also mask ventral/medial vertices that don't face upward.
# normals[:, 1] < 0.3 selects non-dorsal faces (DV axis = 1).
# Uncomment the next line to enable:
# invalid = invalid | (normals[:, 1] < 0.3)

vertex_colors = np.column_stack([r, g, b, np.ones(len(vertices))])
vertex_colors[invalid] = GRAY
vertex_colors = np.clip(vertex_colors, 0.0, 1.0).astype(np.float32)

np.save("vertex_colors.npy", vertex_colors)
print(f"vertex_colors.npy  shape={vertex_colors.shape}  "
      f"({(~invalid).sum()}/{len(vertices)} vertices colored)")

# ============================================================================
# STEP 5 — Quick visual check (top-down scatter plot)
# ============================================================================
import matplotlib.pyplot as plt

fig, axes = plt.subplots(1, 3, figsize=(18, 6))

axes[0].imshow(phase_rgb, origin="lower")
axes[0].set_title("Original phase colormap RGB")

ap = vertices[:, 0]
ml = vertices[:, 2]
axes[1].scatter(ml, ap, c=vertex_colors[:, :3], s=0.05, marker=".")
axes[1].set_aspect("equal")
axes[1].set_title("All vertices (top-down projection)")

valid_mask = ~np.all(np.isclose(vertex_colors[:, :3], 0.15), axis=1)
axes[2].scatter(ml[valid_mask], ap[valid_mask],
                c=vertex_colors[valid_mask, :3], s=0.05, marker=".")
axes[2].set_aspect("equal")
axes[2].set_title("Colored vertices only")

plt.tight_layout()
plt.savefig("interpolation_check.png", dpi=200)
plt.show()
print("Saved interpolation_check.png")
