"""
Step 2: Convert a pre-colored, masked RGBA phase map into per-vertex RGBA
colors for the isocortex mesh, saved as processed_data/vertex_colors.npy.

INPUT FORMAT:
    raw_data/phase_colormap.mat  —  contains 'rgbaImage', an H x W x 4 array:
        channels 0-2 = RGB phase colors (from a cyclic colormap)
        channel  3   = mask alpha (1 inside cortex, 0 outside)
    Generated by scripts/00_phase_to_rgba.m.

    Alternatively, a .npy file with shape (H, W, 4) RGBA float32 is also accepted.

Pipeline:
    1. Load isocortex.obj vertices (N, 3) in Allen CCF µm.
    2. Load phase_colormap.mat → rgbaImage (H x W x 4), RGB + mask alpha.
    3. Interpolate R, G, B, A per vertex at each vertex's (AP, ML) position.
    4. Blend each vertex color: phase_color × alpha + white × (1 − alpha).
       This bakes the mask boundary directly into the color — no transparency
       needed in Blender.
    5. Save vertex_colors.npy — shape (N, 4) RGBA float32, all alpha = 1.

Run in a normal Python env (NOT inside Blender):
    pip install trimesh scipy numpy
    python scripts/02_phasemap_to_vertex_colors.py
"""

import numpy as np
import trimesh
import mat73
from scipy.interpolate import RegularGridInterpolator
from scipy.ndimage import gaussian_filter

# ---------------------------------------------------------------------------
# CONFIG (EDIT THESE)
# ---------------------------------------------------------------------------
MESH_PATH       = "raw_data/isocortex.obj"
PHASE_RGBA_PATH = "raw_data/phase_colormap.mat"   # from scripts/00_phase_to_rgba.m
RGBA_VAR_NAME   = "rgbaImage"                      # variable name inside the .mat
OUT_PATH        = "processed_data/vertex_colors.npy"

# AP / ML extents (µm) that the phase image spans.
AP_MIN, AP_MAX  = 0.0, 13200.0   # 1320 px × 10 µm/px
ML_MIN, ML_MAX  = 0.0, 11400.0   # 1140 px × 10 µm/px

# CCF axis mapping for isocortex.obj (axis 0 = AP, 1 = DV, 2 = ML).
AP_AXIS = 0
ML_AXIS = 2
DV_AXIS = 1   # unused but kept for reference

# Gaussian blur radius (pixels) applied to the mask alpha before interpolation.
# Larger values produce smoother, more rounded edges where the phase map meets white.
MASK_SMOOTH_SIGMA = 30

# Color for vertices outside the cortical mask (blended in at mask boundaries).
OUTSIDE_COLOR = [1.0, 1.0, 1.0]   # white

# ---------------------------------------------------------------------------
# 1. LOAD MESH
# ---------------------------------------------------------------------------
mesh     = trimesh.load(MESH_PATH)
vertices = mesh.vertices        # (N, 3) in CCF µm
normals  = mesh.vertex_normals  # (N, 3)

# ---------------------------------------------------------------------------
# 2. LOAD RGBA PHASE IMAGE
# ---------------------------------------------------------------------------
if PHASE_RGBA_PATH.endswith(".mat"):
    mat = mat73.loadmat(PHASE_RGBA_PATH)
    if RGBA_VAR_NAME not in mat:
        raise KeyError(
            f"'{RGBA_VAR_NAME}' not found in {PHASE_RGBA_PATH}. "
            f"Variables present: {list(mat.keys())}"
        )
    rgba = np.asarray(mat[RGBA_VAR_NAME], dtype=float)
else:
    rgba = np.load(PHASE_RGBA_PATH).astype(float)   # (H, W, 4)

if rgba.ndim != 3 or rgba.shape[2] != 4:
    raise ValueError(f"Expected H x W x 4 RGBA image, got {rgba.shape}")

# Smooth the mask alpha to produce clean, rounded edges at the mask boundary.
rgba = rgba.copy()
rgba[:, :, 3] = gaussian_filter(rgba[:, :, 3].astype(float), sigma=MASK_SMOOTH_SIGMA)

# ---------------------------------------------------------------------------
# 3. PER-CHANNEL INTERPOLATORS
# ---------------------------------------------------------------------------
ap_axis = np.linspace(AP_MIN, AP_MAX, rgba.shape[0])
ml_axis = np.linspace(ML_MIN, ML_MAX, rgba.shape[1])

def make_interp(channel):
    return RegularGridInterpolator(
        (ap_axis, ml_axis), channel,
        method="linear", bounds_error=False, fill_value=np.nan,
    )

interp_r = make_interp(rgba[:, :, 0])
interp_g = make_interp(rgba[:, :, 1])
interp_b = make_interp(rgba[:, :, 2])
interp_a = make_interp(rgba[:, :, 3])

query = np.column_stack([vertices[:, AP_AXIS], vertices[:, ML_AXIS]])
r = interp_r(query)
g = interp_g(query)
b = interp_b(query)
a = interp_a(query)

# ---------------------------------------------------------------------------
# 4. BLEND: phase_color × alpha + white × (1 - alpha)
#    All vertices get alpha=1 — the mask boundary is baked into the RGB color.
# ---------------------------------------------------------------------------
alpha_w = np.nan_to_num(a, nan=0.0).clip(0, 1)   # per-vertex blend weight
rgb     = np.nan_to_num(np.column_stack([r, g, b]), nan=0.0)
outside = np.array(OUTSIDE_COLOR, dtype=np.float32)

blended         = rgb * alpha_w[:, None] + outside * (1.0 - alpha_w[:, None])
vertex_colors   = np.column_stack([blended, np.ones(len(vertices))]).astype(np.float32)
vertex_colors   = np.clip(vertex_colors, 0.0, 1.0)

# ---------------------------------------------------------------------------
# 5. SAVE
# ---------------------------------------------------------------------------
np.save(OUT_PATH, vertex_colors)
print(f"wrote {OUT_PATH}  shape={vertex_colors.shape}")
