"""
Step 2: Convert a pre-colored, masked RGBA phase map into per-vertex RGBA
colors for the isocortex mesh, saved as processed_data/vertex_colors.npy.

INPUT FORMAT:
    raw_data/phase_colormap.mat  —  contains 'rgbaImage', an H x W x 4 array:
        channels 0-2 = RGB phase colors (from a cyclic colormap)
        channel  3   = mask alpha (1 inside cortex, 0 outside)
    Generated by scripts/00_phase_to_rgba.m.

    Alternatively, a .npy file with shape (H, W, 4) RGBA float32 is also accepted.

Pipeline:
    1. Load isocortex.obj vertices (N, 3) in Allen CCF µm.
    2. Load phase_colormap.mat → rgbaImage (H x W x 4), RGB + mask alpha.
    3. Interpolate R, G, B, A per vertex at each vertex's (AP, ML) position.
    4. A vertex is valid only if it is inside the image, inside the mask
       (alpha ≥ threshold), AND facing dorsally. Invalid vertices get alpha 0
       so the Blender material renders them as transparent.
    5. Save vertex_colors.npy — shape (N, 4) RGBA, float32.

Run in a normal Python env (NOT inside Blender):
    pip install trimesh scipy numpy
    python scripts/02_phasemap_to_vertex_colors.py
"""

import numpy as np
import trimesh
from scipy.interpolate import RegularGridInterpolator
from scipy.io import loadmat

# ---------------------------------------------------------------------------
# CONFIG (EDIT THESE)
# ---------------------------------------------------------------------------
MESH_PATH       = "raw_data/isocortex.obj"
PHASE_RGBA_PATH = "raw_data/phase_colormap.mat"   # from scripts/00_phase_to_rgba.m
RGBA_VAR_NAME   = "rgbaImage"                      # variable name inside the .mat
OUT_PATH        = "processed_data/vertex_colors.npy"

# AP / ML extents (µm) that the phase image spans.
AP_MIN, AP_MAX  = 0.0, 13200.0   # 1320 px × 10 µm/px
ML_MIN, ML_MAX  = 0.0, 11400.0   # 1140 px × 10 µm/px

# CCF axis mapping for isocortex.obj (axis 0 = AP, 1 = DV, 2 = ML).
AP_AXIS = 0
ML_AXIS = 2
DV_AXIS = 1

# Vertex must face dorsally (DV normal component above threshold) to be painted.
DORSAL_NORMAL_THRESH = 0.3

# Interpolated alpha at/above this counts as "inside the cortical mask".
ALPHA_THRESH = 0.5

# ---------------------------------------------------------------------------
# 1. LOAD MESH
# ---------------------------------------------------------------------------
mesh     = trimesh.load(MESH_PATH)
vertices = mesh.vertices        # (N, 3) in CCF µm
normals  = mesh.vertex_normals  # (N, 3)

# ---------------------------------------------------------------------------
# 2. LOAD RGBA PHASE IMAGE
# ---------------------------------------------------------------------------
if PHASE_RGBA_PATH.endswith(".mat"):
    mat = loadmat(PHASE_RGBA_PATH)
    if RGBA_VAR_NAME not in mat:
        raise KeyError(
            f"'{RGBA_VAR_NAME}' not found in {PHASE_RGBA_PATH}. "
            f"Variables present: {[k for k in mat if not k.startswith('__')]}"
        )
    rgba = np.asarray(mat[RGBA_VAR_NAME], dtype=float)
else:
    rgba = np.load(PHASE_RGBA_PATH).astype(float)   # (H, W, 4)

if rgba.ndim != 3 or rgba.shape[2] != 4:
    raise ValueError(f"Expected H x W x 4 RGBA image, got {rgba.shape}")

# ---------------------------------------------------------------------------
# 3. PER-CHANNEL INTERPOLATORS
# ---------------------------------------------------------------------------
ap_axis = np.linspace(AP_MIN, AP_MAX, rgba.shape[0])
ml_axis = np.linspace(ML_MIN, ML_MAX, rgba.shape[1])

def make_interp(channel):
    return RegularGridInterpolator(
        (ap_axis, ml_axis), channel,
        method="linear", bounds_error=False, fill_value=np.nan,
    )

interp_r = make_interp(rgba[:, :, 0])
interp_g = make_interp(rgba[:, :, 1])
interp_b = make_interp(rgba[:, :, 2])
interp_a = make_interp(rgba[:, :, 3])

query = np.column_stack([vertices[:, AP_AXIS], vertices[:, ML_AXIS]])
r = interp_r(query)
g = interp_g(query)
b = interp_b(query)
a = interp_a(query)

# ---------------------------------------------------------------------------
# 4. VALIDITY: inside image AND inside mask AND dorsal-facing
# ---------------------------------------------------------------------------
in_fov      = ~np.isnan(r)
in_mask     = np.nan_to_num(a, nan=0.0) >= ALPHA_THRESH
dorsal_face = normals[:, DV_AXIS] > DORSAL_NORMAL_THRESH
valid       = in_fov & in_mask & dorsal_face

# ---------------------------------------------------------------------------
# 5. ASSEMBLE AND SAVE
# ---------------------------------------------------------------------------
vertex_colors          = np.zeros((len(vertices), 4), dtype=np.float32)
rgb                    = np.nan_to_num(np.column_stack([r, g, b]), nan=0.0)
vertex_colors[:, :3]   = rgb
vertex_colors[~valid, :3] = 0.0  # no stray colors outside mask
vertex_colors[valid, 3]   = 1.0  # alpha 1 inside mask, 0 outside
vertex_colors          = np.clip(vertex_colors, 0.0, 1.0)

np.save(OUT_PATH, vertex_colors)
print(f"wrote {OUT_PATH}  shape={vertex_colors.shape}  "
      f"({valid.sum()} / {len(vertices)} vertices inside mask)")
