import bpy
import numpy as np
import os
import mathutils
import math

# ============================================================================
# STYLE: METALLIC / IRIDESCENT
# ============================================================================
# A dramatic, eye-catching style ideal for journal covers and posters.
# The brain is rendered with a pearlescent/iridescent metallic material
# that shifts color based on viewing angle (thin-film interference effect).
# The cortex retains vibrant phase colors with added metallic sheen.
#
# HOW TO RUN:  Blender → Scripting tab → Open this file → Run Script (Alt+P)
# ============================================================================

# ============================================================================
# REQUIRED FILES — place all of these in data_dir before running
# ============================================================================
#   root.obj           — whole-brain outer shell
#   isocortex.obj      — dorsal cortex surface mesh
#   vertex_colors.npy  — per-vertex phase colors
#                        (generated by notebooks/prepare_for_blender.ipynb)
# ============================================================================

# ============================================================================
# CONFIGURATION — edit these before running
# ============================================================================

data_dir           = "/path/to/sample_data"   # ← set to your sample_data folder
VERTEX_COLORS_FILE = "vertex_colors.npy"       # phase map colors per vertex

SAVE_RENDER   = True
RENDER_OUTPUT = os.path.join(data_dir, "render_metallic.png")

# ============================================================================
# PARAMETERS
# ============================================================================

# -- BRAIN (Iridescent metallic) --
BRAIN_ALPHA           = 0.30
BRAIN_COLOR           = (0.75, 0.78, 0.88, 1)  # Cool steel base
BRAIN_ROUGHNESS       = 0.20      # Slightly rough for soft reflections
BRAIN_IOR             = 2.5       # Higher IOR for metallic Fresnel
BRAIN_METALLIC        = 0.65      # High metallic value

# Iridescence parameters
IRID_COLOR_WARM       = (0.85, 0.65, 0.90, 1)  # Purple/pink at glancing angles
IRID_COLOR_COOL       = (0.55, 0.70, 0.95, 1)  # Blue at facing angles
IRID_BLEND            = 0.5       # Fresnel blend strength

# -- CORTEX (Soft BioRender style with transparency) --
CORTEX_ROUGHNESS      = 0.8       # Matte for flat look
CORTEX_SPECULAR       = 0.1      # Minimal specular
CORTEX_EMISSION_STR   = 0.2       # Gentler emission
CORTEX_SATURATION     = 0.9       # Less saturated, softer pastels
CORTEX_VALUE          = 2.0      # Lower brightness
CORTEX_METALLIC       = 0.0       # No metallic
CORTEX_OPACITY        = 0.9       # 0.0 = invisible, 1.0 = fully opaque

# -- OUTLINE PARAMETERS --
HULL_THICKNESS_CORTEX = 80
HULL_THICKNESS_BRAIN  = 80
HULL_MASK_START_Z     = 0.0
HULL_MASK_END_Z       = 2.0
ENABLE_BRAIN_OUTLINE  = True

# -- LIGHTING (Dramatic, directional for metallic highlights) --
OVERHEAD_ENERGY       = 50
OVERHEAD_LOCATION     = (0, 0, -15)
OVERHEAD_SIZE         = 8.0        # Smaller for sharper highlights
OVERHEAD_COLOR        = (1.0, 0.98, 0.95)

ACCENT1_ENERGY        = 50
ACCENT1_LOCATION      = (-4, 3, -8)
ACCENT1_SIZE          = 6.0
ACCENT1_COLOR         = (1.0, 0.90, 0.85)  # Warm accent

ACCENT2_ENERGY        = 50
ACCENT2_LOCATION      = (-4, -3, -8)
ACCENT2_SIZE          = 6.0
ACCENT2_COLOR         = (0.85, 0.88, 1.0)  # Cool accent

RIM_ENERGY            = 30        # Stronger rims for metallic
RIM_LOCATION          = (-6, -4, -2)
RIM_SIZE              = 3.0
RIM_COLOR             = (1.0, 0.95, 0.90)

RIM_LEFT_ENERGY       = 30
RIM_LEFT_LOCATION     = (6, -4, -2)
RIM_LEFT_SIZE         = 3.0
RIM_LEFT_COLOR        = (0.90, 0.95, 1.0)

RIM_BACK_LEFT_ENERGY    = 50
RIM_BACK_LEFT_LOCATION  = (6, 4, -2)
RIM_BACK_LEFT_SIZE      = 5.0
RIM_BACK_LEFT_COLOR     = (0.88, 0.85, 1.0)

RIM_BACK_RIGHT_ENERGY   = 50
RIM_BACK_RIGHT_LOCATION = (-6, 4, -2)
RIM_BACK_RIGHT_SIZE     = 5.0
RIM_BACK_RIGHT_COLOR    = (1.0, 0.88, 0.85)

RIM_BACK_CENTER_ENERGY   = 120
RIM_BACK_CENTER_LOCATION = (8, 0, -4)
RIM_BACK_CENTER_SIZE     = 8.0
RIM_BACK_CENTER_COLOR    = (0.95, 0.93, 1.0)

# -- CAMERA --
CAM_HEIGHT            = 45
CAM_TYPE              = 'PERSP'
CAM_FOCAL_LENGTH      = 28

# -- RENDER --
RENDER_ENGINE         = 'BLENDER_EEVEE'
TRANSPARENT_BG        = True
RENDER_SAMPLES        = 64
RESOLUTION_X          = 1500
RESOLUTION_Y          = 1800
WORLD_STRENGTH        = 0.25
WORLD_COLOR           = (0.015, 0.01, 0.025)  # Dark purple-tinted background

# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

def safe_set_input(node, names, value):
    if isinstance(names, str):
        names = [names]
    for name in names:
        if name in node.inputs:
            node.inputs[name].default_value = value
            return

def create_hull_material(name, z_start, z_end):
    mat = bpy.data.materials.new(name)
    mat.use_nodes = True
    mat.use_backface_culling = True
    mat.show_transparent_back = False
    if hasattr(mat, 'blend_method'):
        mat.blend_method = 'BLEND'
    if hasattr(mat, 'shadow_method'):
        mat.shadow_method = 'NONE'

    nodes = mat.node_tree.nodes
    links = mat.node_tree.links
    nodes.clear()

    out = nodes.new('ShaderNodeOutputMaterial')
    mix = nodes.new('ShaderNodeMixShader')
    emission = nodes.new('ShaderNodeEmission')
    transparent = nodes.new('ShaderNodeBsdfTransparent')
    emission.inputs['Color'].default_value = (0, 0, 0, 1)

    sep = nodes.new('ShaderNodeSeparateXYZ')
    geom = nodes.new('ShaderNodeNewGeometry')
    map_range = nodes.new('ShaderNodeMapRange')

    links.new(geom.outputs['Position'], sep.inputs['Vector'])
    map_range.inputs['From Min'].default_value = z_start
    map_range.inputs['From Max'].default_value = z_end
    map_range.inputs['To Min'].default_value = 0.0
    map_range.inputs['To Max'].default_value = 1.0
    map_range.clamp = True

    links.new(sep.outputs['Z'], map_range.inputs['Value'])
    links.new(map_range.outputs['Result'], mix.inputs['Fac'])
    links.new(emission.outputs['Emission'], mix.inputs[1])
    links.new(transparent.outputs['BSDF'], mix.inputs[2])
    links.new(mix.outputs['Shader'], out.inputs['Surface'])

    return mat

def add_hull_modifier(obj, material_index, thickness):
    mod = obj.modifiers.new(name="Outline_Hull", type='SOLIDIFY')
    mod.thickness = thickness
    mod.offset = 1.0
    mod.use_flip_normals = True
    mod.material_offset = material_index
    mod.use_rim = False
    mod.use_even_offset = True
    mod.use_quality_normals = True
    mod.shell_vertex_group = ""

# ============================================================================
# SETUP SCRIPT
# ============================================================================

# 1. CLEANUP
bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.delete()
for block in [bpy.data.meshes, bpy.data.materials, bpy.data.lights,
              bpy.data.cameras, bpy.data.collections, bpy.data.linestyles]:
    for item in block:
        try: block.remove(item)
        except: pass

# 2. COLLECTIONS
main_coll = bpy.context.scene.collection
cortex_coll = bpy.data.collections.new("Cortex_Collection")
brain_coll = bpy.data.collections.new("Brain_Collection")
lights_coll = bpy.data.collections.new("Lights_Collection")
main_coll.children.link(cortex_coll)
main_coll.children.link(brain_coll)
main_coll.children.link(lights_coll)

# 3. PIVOT
brain_pivot = bpy.data.objects.new("Brain_Pivot", None)
main_coll.objects.link(brain_pivot)
brain_pivot.location = (0,0,0)

# 4. IMPORT & GEOMETRY
imported_objects = {}
for obj_file, name, target_coll in [("root.obj", "Brain", brain_coll),
                                    ("isocortex.obj", "Cortex", cortex_coll)]:
    full_path = os.path.join(data_dir, obj_file)
    if not os.path.exists(full_path):
        print(f"WARNING: {full_path} not found.")
        continue
    bpy.ops.wm.obj_import(filepath=full_path)
    imported = bpy.context.selected_objects
    for obj in imported:
        obj.name = name
        for coll in obj.users_collection:
            coll.objects.unlink(obj)
        target_coll.objects.link(obj)
        obj.scale = (0.001, 0.001, 0.001)
        obj.parent = brain_pivot
        bpy.ops.object.shade_smooth()
        weld = obj.modifiers.new(name="Weld_Geometry", type='WELD')
        weld.merge_threshold = 0.01
        if hasattr(obj.data, 'use_auto_smooth'):
             obj.data.use_auto_smooth = True
             obj.data.auto_smooth_angle = math.radians(60)
        else:
            try:
                bpy.context.view_layer.objects.active = obj
                bpy.ops.object.modifier_add(type='SMOOTH_BY_ANGLE')
            except: pass
        imported_objects[name] = obj

# 5. MATERIALS
hull_mat = create_hull_material("Hull_Ink", z_start=HULL_MASK_START_Z, z_end=HULL_MASK_END_Z)

# --- BRAIN: Iridescent Metallic ---
if "Brain" in imported_objects:
    obj = imported_objects["Brain"]
    mat = bpy.data.materials.new("BrainMat_Iridescent")
    mat.use_nodes = True
    mat.use_backface_culling = False
    if hasattr(mat, 'blend_method'):
        mat.blend_method = 'BLEND'
    if hasattr(mat, 'shadow_method'):
        mat.shadow_method = 'NONE'
    mat.show_transparent_back = False

    nodes = mat.node_tree.nodes
    links = mat.node_tree.links
    nodes.clear()

    out = nodes.new('ShaderNodeOutputMaterial')
    
    # --- Iridescent effect via Fresnel-driven color mixing ---
    bsdf = nodes.new('ShaderNodeBsdfPrincipled')
    
    # Fresnel-based color shift (simulates thin-film interference)
    layer_weight = nodes.new('ShaderNodeLayerWeight')
    layer_weight.inputs['Blend'].default_value = IRID_BLEND
    
    # Mix between warm and cool colors based on viewing angle
    color_mix = nodes.new('ShaderNodeMixRGB')
    color_mix.blend_type = 'MIX'
    color_mix.inputs[1].default_value = IRID_COLOR_COOL   # Facing
    color_mix.inputs[2].default_value = IRID_COLOR_WARM    # Glancing
    
    links.new(layer_weight.outputs['Fresnel'], color_mix.inputs['Fac'])
    
    # Feed iridescent color into Principled BSDF
    links.new(color_mix.outputs['Color'], bsdf.inputs['Base Color'])
    safe_set_input(bsdf, ['Metallic'], BRAIN_METALLIC)
    safe_set_input(bsdf, 'Roughness', BRAIN_ROUGHNESS)
    safe_set_input(bsdf, 'IOR', BRAIN_IOR)
    safe_set_input(bsdf, 'Alpha', BRAIN_ALPHA)
    
    # Add a subtle color ramp for extra iridescence depth
    # Thin-film-like: add a second layer weight for specular tint
    specular_tint_mix = nodes.new('ShaderNodeMixRGB')
    specular_tint_mix.blend_type = 'MIX'
    specular_tint_mix.inputs[1].default_value = (0.6, 0.7, 1.0, 1)  # Blue specular
    specular_tint_mix.inputs[2].default_value = (1.0, 0.6, 0.8, 1)  # Pink specular
    
    fresnel2 = nodes.new('ShaderNodeFresnel')
    fresnel2.inputs['IOR'].default_value = 1.8
    
    links.new(fresnel2.outputs['Fac'], specular_tint_mix.inputs['Fac'])
    
    # Mix metallic BSDF with transparent for see-through effect
    mix_final = nodes.new('ShaderNodeMixShader')
    transparent = nodes.new('ShaderNodeBsdfTransparent')
    transparent.inputs['Color'].default_value = (0.85, 0.88, 0.95, 1)
    
    mix_final.inputs['Fac'].default_value = 0.35  # 35% opaque metallic
    links.new(transparent.outputs['BSDF'], mix_final.inputs[1])
    links.new(bsdf.outputs['BSDF'], mix_final.inputs[2])
    
    links.new(mix_final.outputs['Shader'], out.inputs['Surface'])

    obj.data.materials.append(mat)
    if ENABLE_BRAIN_OUTLINE:
        obj.data.materials.append(hull_mat)
        add_hull_modifier(obj, 1, HULL_THICKNESS_BRAIN)

# --- CORTEX: Soft BioRender style (emission + transparency) ---
if "Cortex" in imported_objects:
    obj = imported_objects["Cortex"]
    npy_path = os.path.join(data_dir, VERTEX_COLORS_FILE)
    if os.path.exists(npy_path):
        colors = np.load(npy_path)
        mesh = obj.data
        if not mesh.vertex_colors:
            mesh.vertex_colors.new(name="Phase")
        color_layer = mesh.vertex_colors["Phase"]
        for poly in mesh.polygons:
            for loop_idx in poly.loop_indices:
                vi = mesh.loops[loop_idx].vertex_index
                if vi < len(colors):
                    color_layer.data[loop_idx].color = colors[vi]

        mat = bpy.data.materials.new("PhaseMat_BioRender")
        mat.use_nodes = True
        
        # CRITICAL: Enable blend mode for EEVEE transparency
        if hasattr(mat, 'blend_method'):
            mat.blend_method = 'BLEND'
        if hasattr(mat, 'shadow_method'):
            mat.shadow_method = 'NONE'
        mat.show_transparent_back = False
        
        nodes = mat.node_tree.nodes
        links = mat.node_tree.links
        nodes.clear()

        out = nodes.new('ShaderNodeOutputMaterial')
        vcol = nodes.new('ShaderNodeAttribute')
        hsv = nodes.new('ShaderNodeHueSaturation')
        emission = nodes.new('ShaderNodeEmission')
        transparent = nodes.new('ShaderNodeBsdfTransparent')
        mix_final = nodes.new('ShaderNodeMixShader')

        vcol.attribute_name = "Phase"
        hsv.inputs['Saturation'].default_value = CORTEX_SATURATION
        hsv.inputs['Value'].default_value = CORTEX_VALUE
        emission.inputs['Strength'].default_value = CORTEX_EMISSION_STR
        transparent.inputs['Color'].default_value = (1, 1, 1, 1)

        # Opacity control: Fac = how much emission vs transparent
        mix_final.inputs['Fac'].default_value = CORTEX_OPACITY

        # Node chain: VertexColor -> HSV -> Emission -> Mix with Transparent -> Output
        links.new(vcol.outputs['Color'], hsv.inputs['Color'])
        links.new(hsv.outputs['Color'], emission.inputs['Color'])
        links.new(transparent.outputs['BSDF'], mix_final.inputs[1])   # Fac=0 -> transparent
        links.new(emission.outputs['Emission'], mix_final.inputs[2])  # Fac=1 -> emission
        links.new(mix_final.outputs['Shader'], out.inputs['Surface'])

        obj.data.materials.append(mat)
        obj.data.materials.append(hull_mat)
        add_hull_modifier(obj, 1, HULL_THICKNESS_CORTEX)

# 6. CENTERING
if "Brain" in imported_objects:
    brain_obj = imported_objects["Brain"]
    depsgraph = bpy.context.evaluated_depsgraph_get()
    brain_eval = brain_obj.evaluated_get(depsgraph)
    bbox_corners = [brain_obj.matrix_world @ mathutils.Vector(corner) for corner in brain_eval.bound_box]
    bbox_center = sum(bbox_corners, mathutils.Vector((0, 0, 0))) / 8
    for child in brain_pivot.children:
        child.location = child.location - bbox_center

# 7. DISABLE FREESTYLE
view_layer = bpy.context.view_layer
view_layer.use_freestyle = False

# 8. LIGHTING
world = bpy.context.scene.world
if not world: world = bpy.data.worlds.new("World")
bpy.context.scene.world = world
world.use_nodes = True
bg = world.node_tree.nodes['Background']
bg.inputs['Color'].default_value = (*WORLD_COLOR, 1)
bg.inputs['Strength'].default_value = WORLD_STRENGTH

def add_light(name, energy, loc, size, color, shadows=True):
    data = bpy.data.lights.new(name=name, type='AREA')
    data.energy = energy
    data.color = color
    data.size = size
    if not shadows: data.use_shadow = False
    obj = bpy.data.objects.new(name, data)
    lights_coll.objects.link(obj)
    obj.location = loc
    con = obj.constraints.new(type='TRACK_TO')
    con.target = brain_pivot
    con.track_axis = 'TRACK_NEGATIVE_Z'
    con.up_axis = 'UP_Y'
    return obj

add_light("Overhead", OVERHEAD_ENERGY, OVERHEAD_LOCATION, OVERHEAD_SIZE, OVERHEAD_COLOR, shadows=True)
add_light("Accent_Left", ACCENT1_ENERGY, ACCENT1_LOCATION, ACCENT1_SIZE, ACCENT1_COLOR, shadows=False)
add_light("Accent_Right", ACCENT2_ENERGY, ACCENT2_LOCATION, ACCENT2_SIZE, ACCENT2_COLOR, shadows=False)
add_light("Rim_Front_R", RIM_ENERGY, RIM_LOCATION, RIM_SIZE, RIM_COLOR, shadows=False)
add_light("Rim_Front_L", RIM_LEFT_ENERGY, RIM_LEFT_LOCATION, RIM_LEFT_SIZE, RIM_LEFT_COLOR, shadows=False)
add_light("Rim_Back_L", RIM_BACK_LEFT_ENERGY, RIM_BACK_LEFT_LOCATION, RIM_BACK_LEFT_SIZE, RIM_BACK_LEFT_COLOR, shadows=False)
add_light("Rim_Back_R", RIM_BACK_RIGHT_ENERGY, RIM_BACK_RIGHT_LOCATION, RIM_BACK_RIGHT_SIZE, RIM_BACK_RIGHT_COLOR, shadows=False)
add_light("Rim_Back_C", RIM_BACK_CENTER_ENERGY, RIM_BACK_CENTER_LOCATION, RIM_BACK_CENTER_SIZE, RIM_BACK_CENTER_COLOR, shadows=False)

# 9. RENDER & CAMERA
scene = bpy.context.scene
scene.render.engine = RENDER_ENGINE
scene.render.resolution_x = RESOLUTION_X
scene.render.resolution_y = RESOLUTION_Y
scene.render.film_transparent = TRANSPARENT_BG

if RENDER_ENGINE == 'BLENDER_EEVEE':
    if hasattr(scene.eevee, 'taa_render_samples'):
        scene.eevee.taa_render_samples = RENDER_SAMPLES
    if hasattr(scene.eevee, 'use_bloom'):
        scene.eevee.use_bloom = True
        scene.eevee.bloom_threshold = 0.7
        scene.eevee.bloom_intensity = 0.15  # More bloom for metallic glow
    if hasattr(scene.eevee, 'use_ssr'):
        scene.eevee.use_ssr = True
        scene.eevee.use_ssr_refraction = True

cam_data = bpy.data.cameras.new("Camera")
cam_obj = bpy.data.objects.new("Camera", cam_data)
main_coll.objects.link(cam_obj)
scene.camera = cam_obj
# cam_obj.location = (0, 0, -CAM_HEIGHT)
# cam_obj.rotation_euler = (math.pi, 0, -math.pi/2)

cam_obj.location = (2.4583, -4.8708, -15.1973)
cam_obj.rotation_euler = (0.3491, 3.1416, 0.5515)

cam_data.type = CAM_TYPE
cam_data.lens = CAM_FOCAL_LENGTH

print("=" * 50)
print("STYLE 3: METALLIC / IRIDESCENT COMPLETE")
print("  - Brain: Fresnel-driven iridescent color shift (cool<->warm)")
print("  - Cortex: Metallic-sheen phase map with partial metallic BSDF")
print("  - Lighting: Smaller, directional lights for dramatic highlights")
print("=" * 50)

# ============================================================================
# 10. SAVE RENDER
# ============================================================================
# SAVE_RENDER and RENDER_OUTPUT are set in the CONFIGURATION section at the top.
# To capture a new camera angle: frame it in the 3D viewport, run
# scripts/extract_camera_params.py (MODE = 'viewport'), and paste the printed
# values into the cam_obj.location / .rotation_euler lines in section 9.

if SAVE_RENDER:
    scene.render.image_settings.file_format = 'PNG'
    scene.render.image_settings.color_depth = '16'
    scene.render.filepath = RENDER_OUTPUT
    bpy.ops.render.render(write_still=True)
    print(f"Saved render to: {RENDER_OUTPUT}")
